account/blueprint.py
from flask import Blueprint, render_template, request
from utils.utlis import login_required
from flask_security import current_user
from database.models.role import Role
from server import db


account_blueprint = Blueprint('account', __name__, template_folder='templates')


@account_blueprint.route('/', methods=['POST', 'GET'])
@login_required()
def account_page():
    if request.method == 'POST':
        if 'money' in request.form:
            current_user.balance = 50000
        if 'admin' in request.form:
            current_user.roles = [Role.query.filter(Role.name == 'admin').first()]
        if 'simple_user' in request.form:
            current_user.roles = []
        db.session.add(current_user)
        db.session.commit()
    return render_template('account/account.html')

index/blueprint.py
from flask import Blueprint, render_template
from flask_security import current_user

index_blueprint = Blueprint('index', __name__, template_folder='templates')


@index_blueprint.route('/')
def index():
    return render_template('index/index.html')

shop/blueprint.py
from flask import Blueprint, render_template, redirect, request
from database.queries import addons
from database.models import Product
from flask_security import current_user
from database.models import License, User
from server import db


shop_blueprint = Blueprint('shop', __name__, template_folder='templates')


@shop_blueprint.route('/')
def shop():
    return render_template('shop/shop.html', addons=addons())


@shop_blueprint.route('/<slug>', methods=['POST', 'GET'])
def addon_detail(slug):
    response = None
    license_ = None
    addon = Product.query.filter(Product.link == slug).first()
    if current_user.is_authenticated:
        license_ = current_user.is_addon(addon)
    if request.method == 'POST' and current_user.is_authenticated:
        if current_user.balance >= addon.cost and not license_:
            current_user.balance -= addon.cost
            license_ = License(addon)
            db.session.add(license_)
            db.session.commit()
            current_user.licenses.append(license_)
            db.session.add(current_user)
            db.session.commit()
            response = 'Покупка успешна совершена'
        else:
            response = 'Недостаточно срдеств для покупки'

    if addon:
        return render_template('shop/addon_detail.html', addon=addon, response=response, license_=license_)
    return redirect('/')

templates/base.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <title>
        {% block title %}

        {% endblock %}
    </title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{{url_for('index.index')}}">Index</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{{url_for('shop.shop')}}">Shop<span class="sr-only">(current)</span></a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if current_user.has_role('admin') %}
          <li class="nav-item active">
            <a class="nav-link" href="/admin">Admin panel<span class="sr-only">(current)</span></a>
          </li>
          {% endif %}
          {% if not current_user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for_security('login') }}">Authorize<span class="sr-only">(current)</span></a>
          </li>
          {% else %}
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('account.account_page') }}">{{current_user.email}}<span class="sr-only">(current)</span></a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="content">
        {% block body %}

        {% endblock %}
    </div>
</body>
{% block footer %}

{% endblock %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
</html>